#mysql - db1
spring:
  datasource:
    hikari:
      db1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db1?&characterEncoding=UTF-8
        username: root
        password: "0000"

      #H2 - db2
      db2:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:db2
        username: sa
        password:
  h2:
    console:
      enabled: true   # ? ??? true? ??
      path: /h2-console  # ? ?? ?? (??: /h2-console)
  jpa:
    hibernate:
      ddl-auto: update # ??????? ?? ???? ?? ???? ??? ???? ?? ?? ??

#    properties:
#      hibernate:
#        show_sql: true # sql?? db? ???? ?? system.out?? ?? ??
#        format_sql: true # ??? ?? ?? ?? ??? sql?? ???? ??? ? ? ??